apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{projectName}}-app
  labels:
    app: {{projectName}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{projectName}}
  template:
    metadata:
      labels:
        app: {{projectName}}
    spec:
      containers:
        - name: app
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/{{projectName}}-eks:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
