apiVersion: v1
kind: Service
metadata:
  name: {{projectName}}-service
  labels:
    app: {{projectName}}
spec:
  type: LoadBalancer
  selector:
    app: {{projectName}}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
